#!/bin/bash
set -e
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
GOOS=linux GOARCH=amd64 CC=musl-gcc gogo build -v -ldflags="-linkmode external -extldflags '-static'" -o bin/build/fun .
./taskforce prod
cat asset.zip >> bin/build/fun