#!/bin/bash
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )

ssh1="root@direct.cjjackson.dev"

./doTest && ./build && \
  scp bin/build/fun "$ssh1:~/service/fun/app" && \
  ssh $ssh1 "~/service/fun/testRun" && \
  ssh $ssh1 "~/service/fun/syncService && echo success"