#!/bin/bash
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
if [ -d "nodeBin" ]; then
    rm -rf nodeBin
fi
mkdir nodeBin
cd nodeBin
wget https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.xz
tar -xJvf node-v*-linux-x64.tar.xz
ln -s node-v*-linux-x64 node
../asset/npm install -g yarn@1.22.4