// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Index.html
	Index = `H4sIAAAAAAAC/0SQMU/EMAyF9/4Kn3ca3caQZAEONk7oTogxtIbkcJMjdpH671FJJSZb73vye7Ld
3T/fnd6ODxB1Yt/ZdQCH/OmQMq4ChdF3AAB2Ig0wxFCF1OH5dLi5xQ1pUiZ/IOJzTt8zwbF/6eGR
MtWgpVrTDM3MKX9BJXYoujBJJFKEWOnDofmXZNv7QWRtYloV+17GZbsU9/6JmAu8lsrjzpq4911D
MtR0VdDlSg6nMs5MCFIHh+YSfkLDYqaQcn8R9NY0aQ1qCdb8/eQ3AAD//5Um/bUjAQAA`
)
