// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Pr.txt
	Pr = `H4sIAAAAAAAC/6yRTUvDQBCG7/0VA150Ick9t9giWqq0EU8iYZpM7dLNbrofrSXZ/y5rA2nxpjks
w7wv8zyH7YCxFWMQZhbmpIui6OdNOpg/5Rl00LagUX4SxHOucSoIJXjP2HvbQgzef9xurW1MmiQb
IuEk3zuK0Qo0hqOMJdlkrdXRUNIf3DEWoCQr8D44YcHljipY5le6c7rUg7IH9PfCEHhfvCRZcY3L
SaD9zevjPwCnz69nEt9APK0NeJ9uCQ+notxSuStq1Lt0IPRd7YTljeAlWq5k8ZVeQ2f3A3O2HgW5
4AeCByWEOkauGfAhP8dvzSiiJWqsyZI2g+QiG0OR095xTQZKoVzFJeoTuEYorC6+Yqj+r5zcwIxM
qXkTyrA+qiNYBZaMDesq+w4AAP//Qt6PBzADAAA=`
)
